name: Push to TrueFoundry when data is updated
on:
  push:
      paths:
        - train_and_deploy/Data/*.csv
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install servicefoundry==0.3.3
    - name: Run Deplyment Code
      env:
        WORKSPACE_FQN : ${{ secrets.WORKSPACE_FQN }}
        TFY_API_KEY : ${{ secrets.TFY_API_KEY }}
      run: |
        cd train_and_deploy
        python deploy_job.py
        